import json
import csv
import hashlib
import sys
import os
from collections import Counter

# Add parent directory to path to import normalization module
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from normalization import normalize_for_search
from solve_ambiguity import resolve_ambiguous, get_resolution_type

# --- إعدادات ---
INPUT_JSON = "Bukhari/Bukhari_Without_Tashkel_results_advanced_with_matn.json"
OUTPUT_JSON = "Bukhari/Bukhari_Normalized_Ready_For_Graph.json"
UNMAPPED_REPORT = "Bukhari/unmapped_narrators_report.csv"
MAPPINGS_FILE = "narrator_mappings.json"
CONTEXT_MAPPINGS_FILE = "Bukhari/resolved_context_mappings.json"

# Load narrator mappings from JSON file
def load_narrator_mappings():
    """Load narrator name mappings from JSON file."""
    try:
        with open(MAPPINGS_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
            # Filter out comment keys (starting with _comment)
            mappings = {k: v for k, v in data['mappings'].items() if not k.startswith('_comment')}
            return mappings, data.get('special_cases', {})
    except FileNotFoundError:
        print(f"⚠️  Warning: {MAPPINGS_FILE} not found. Using empty mappings.")
        return {}, {}
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing {MAPPINGS_FILE}: {e}")
        return {}, {}

def load_context_mappings():
    """Load context-aware disambiguation mappings generated by solve_ambiguity.py."""
    try:
        with open(CONTEXT_MAPPINGS_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f)
            return data.get('context_mappings', {})
    except FileNotFoundError:
        print(f"ℹ️  {CONTEXT_MAPPINGS_FILE} not found. Context resolution disabled.")
        return {}
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing {CONTEXT_MAPPINGS_FILE}: {e}")
        return {}

# Load mappings at module level
NAME_MAPPING, SPECIAL_CASES = load_narrator_mappings()
CONTEXT_MAPPINGS = load_context_mappings()

# Legacy inline dictionary (kept for reference, but JSON takes precedence)
# قاموس التوحيد - الآن محفوظ في narrator_mappings.json
LEGACY_NAME_MAPPING = {
    # === Top 20 Most Frequent (Original + New) ===
    'سفيان': 'سفيان الثوري',  # 798 mentions - الأكثر شيوعاً في البخاري
    'هشام': 'هشام بن عروة',  # 428 mentions
    'يحيى': 'يحيى بن سعيد القطان',  # 407 mentions
    'عبد الله بن عمر': 'عبد الله بن عمر',  # 285 mentions - الشكل الكامل
    'إبراهيم': 'إبراهيم النخعي',  # 237 mentions
    'عمرو': 'عمرو بن دينار',  # 213 mentions
    'عبيد الله': 'عبيد الله بن عمر',  # 210 mentions
    'يحيى بن بكير': 'يحيى بن بكير',  # 204 mentions
    'أبو إسحاق': 'أبو إسحاق السبيعي',  # 195 mentions
    'عبد الله بن محمد': 'عبد الله بن محمد المسندي',  # 188 mentions
    'عكرمة': 'عكرمة مولى ابن عباس',  # 172 mentions
    'سعيد بن جبير': 'سعيد بن جبير',  # 171 mentions
    'يحيى بن سعيد': 'يحيى بن سعيد القطان',  # 171 mentions
    'أبو سعيد الخدري': 'أبو سعيد الخدري',  # 168 mentions
    'آدم': 'آدم بن أبي إياس',  # 163 mentions
    'محمد': 'محمد بن سيرين',  # 163 mentions - افتراض
    'الأعرج': 'عبد الرحمن بن هرمز الأعرج',  # 160 mentions
    'أبو الزناد': 'عبد الله بن ذكوان أبو الزناد',  # 159 mentions

    # === Original High-Frequency Names ===
    'أبو هريرة': 'أبو هريرة',
    'عائشة': 'عائشة بنت أبي بكر',
    'شعبة': 'شعبة بن الحجاج',
    'الزهري': 'محمد بن مسلم الزهري',
    'ابن شهاب': 'محمد بن مسلم الزهري',
    'ابن عباس': 'عبد الله بن عباس',
    'مالك': 'مالك بن أنس',
    'ابن عمر': 'عبد الله بن عمر',
    'أنس بن مالك': 'أنس بن مالك',
    'أنس': 'أنس بن مالك',
    'نافع': 'نافع مولى ابن عمر',
    'الليث': 'الليث بن سعد',
    'الأعمش': 'سليمان بن مهران الأعمش',
    'قتادة': 'قتادة بن دعامة',
    'عبد الله بن يوسف': 'عبد الله بن يوسف التنيسي',
    'عروة بن الزبير': 'عروة بن الزبير',
    'عروة': 'عروة بن الزبير',
    'معمر': 'معمر بن راشد',
    'مسدد': 'مسدد بن مسرهد',
    'علي بن عبد الله': 'علي بن عبد الله المديني',
    'جابر بن عبد الله': 'جابر بن عبد الله',
    'ابن جريج': 'عبد الملك بن جريج',
    'موسى بن إسماعيل': 'موسى بن إسماعيل التبوذكي',
    'هشام بن عروة': 'هشام بن عروة',
    'سعيد بن المسيب': 'سعيد بن المسيب',
    'أبو سلمة': 'أبو سلمة بن عبد الرحمن',
    'قتيبة بن سعيد': 'قتيبة بن سعيد',
    'حماد بن زيد': 'حماد بن زيد',
    'إسماعيل': 'إسماعيل بن أبي أويس',  # ⚠️ افتراض - قد يحتاج تدقيق
    'أبو نعيم': 'أبو نعيم الفضل بن دكين',
    'أبو أسامة': 'أبو أسامة حماد بن أسامة',
    'منصور': 'منصور بن المعتمر',
    'عقيل': 'عقيل بن خالد',
    'يونس': 'يونس بن يزيد',
    'شعيب': 'شعيب بن أبي حمزة',
    'أيوب': 'أيوب السختياني',
    'الحكم بن نافع': 'الحكم بن نافع',
    'محمد بن بشار': 'محمد بن بشار بندار',

    # === Additional Common Narrators (Based on Bukhari Frequency) ===
    'حماد': 'حماد بن زيد',  # يرجح أنه حماد بن زيد في البخاري
    'سعيد': 'سعيد بن المسيب',  # الأكثر شيوعاً
    'وهب': 'وهب بن جرير',
    'ابن المبارك': 'عبد الله بن المبارك',
    'ابن أبي ذئب': 'محمد بن عبد الرحمن بن أبي ذئب',
    'الثوري': 'سفيان الثوري',
    'سفيان بن عيينة': 'سفيان بن عيينة',
    'ابن وهب': 'عبد الله بن وهب',
    'أبو معاوية': 'أبو معاوية محمد بن خازم',
    'وكيع': 'وكيع بن الجراح',
    'عبد الرزاق': 'عبد الرزاق بن همام',
    'يزيد بن هارون': 'يزيد بن هارون',
    'حجاج بن منهال': 'حجاج بن منهال',
    'أبو بكر بن أبي شيبة': 'أبو بكر بن أبي شيبة',
    'محمد بن عبد الله': 'محمد بن عبد الله الأنصاري',
    'عبد الله بن مسلمة': 'عبد الله بن مسلمة القعنبي',
    'أبو اليمان': 'أبو اليمان الحكم بن نافع',
    'صدقة بن الفضل': 'صدقة بن الفضل',
    'محمد بن يوسف': 'محمد بن يوسف الفريابي',
    'أبو الوليد': 'أبو الوليد هشام بن عبد الملك',

    # === Round 2: Next Most Frequent (from latest analysis) ===
    'جرير': 'جرير بن عبد الحميد',  # 159 mentions
    'قتيبة': 'قتيبة بن سعيد',  # 145 mentions - short form
    'همام': 'همام بن يحيى',  # 145 mentions
    'سليمان بن حرب': 'سليمان بن حرب',  # 143 mentions
    'أبو وائل': 'أبو وائل شقيق بن سلمة',  # 141 mentions
    'سليمان': 'سليمان بن حرب',  # 140 mentions - يرجح
    'عطاء': 'عطاء بن أبي رباح',  # 139 mentions
    'أبو حازم': 'أبو حازم سلمة بن دينار',  # 134 mentions
    'سالم': 'سالم بن عبد الله بن عمر',  # 131 mentions
    'إبراهيم بن سعد': 'إبراهيم بن سعد',  # 130 mentions
    'أبو سلمة بن عبد الرحمن': 'أبو سلمة بن عبد الرحمن',  # 127 mentions - full form
    'غندر': 'غندر محمد بن جعفر',  # 127 mentions
    'علي': 'علي بن المديني',  # 123 mentions - يرجح في شيوخ البخاري
    'أبو عوانة': 'أبو عوانة الوضاح بن عبد الله',  # 122 mentions
    'مسروق': 'مسروق بن الأجدع',  # 121 mentions
    'حميد': 'حميد الطويل',  # 119 mentions
    'مجاهد': 'مجاهد بن جبر',  # 118 mentions
    'أبان': 'أبان بن يزيد',  # common in Bukhari
    'جرير بن حازم': 'جرير بن حازم',
    'عمر بن حفص': 'عمر بن حفص بن غياث',

    # === Round 3: Push to 60%+ Coverage ===
    'إسحاق': 'إسحاق بن راهويه',  # 117 mentions - أو إسحاق بن منصور
    'عبدان': 'عبدان بن عثمان',  # 114 mentions
    'وهيب': 'وهيب بن خالد',  # 112 mentions
    'جابر': 'جابر بن عبد الله',  # 112 mentions - same as full form
    'أبو موسى': 'أبو موسى الأشعري',  # 110 mentions
    'محمد بن المثنى': 'محمد بن المثنى العنزي',  # 107 mentions
    'موسى بن عقبة': 'موسى بن عقبة',  # 107 mentions
    'أبو صالح': 'أبو صالح السمان',  # 106 mentions - ذكوان
    'الشعبي': 'عامر بن شراحيل الشعبي',  # 105 mentions
    'خالد': 'خالد بن الحارث',  # 103 mentions - الأكثر في البخاري
    'أبو النعمان': 'أبو النعمان محمد بن الفضل',  # 98 mentions
    'البراء': 'البراء بن عازب',  # 96 mentions
    'عبد الوارث': 'عبد الوارث بن سعيد',  # 94 mentions
    'عبيد الله بن عبد الله': 'عبيد الله بن عبد الله بن عتبة',  # 93 mentions
    'عبد الله بن دينار': 'عبد الله بن دينار',  # 89 mentions
    'عبد العزيز بن عبد الله': 'عبد العزيز بن عبد الله الأويسي',  # 89 mentions
    'إسرائيل': 'إسرائيل بن يونس',  # 85 mentions
    'خالد بن الحارث': 'خالد بن الحارث',  # same as خالد
    'محمود': 'محمود بن غيلان',
    'عبد الله بن رجاء': 'عبد الله بن رجاء',
    'محمد بن سلام': 'محمد بن سلام البيكندي',
    'بشر بن محمد': 'بشر بن محمد السختياني',
    'أبو كريب': 'أبو كريب محمد بن العلاء',
    'ابن أبي عدي': 'محمد بن إبراهيم بن أبي عدي',
    'محمد بن كثير': 'محمد بن كثير العبدي',
    'أبو قلابة': 'أبو قلابة عبد الله بن زيد',
    'طلحة': 'طلحة بن مصرف',
    'ابن نمير': 'عبد الله بن نمير',
    'زهير': 'زهير بن معاوية',
    'الحسن': 'الحسن البصري',
}

def generate_narrator_id(name):
    """
    Generates a consistent ID based on the narrator's name hash.
    Uses SHA-256 with 12 characters to reduce collision probability.
    """
    hash_val = hashlib.sha256(name.encode('utf-8')).hexdigest()[:12].upper()
    return f"NAR_{hash_val}"

def generate_unmapped_report(all_raw_names):
    """
    Generate a report of high-frequency names that weren't mapped.
    This helps identify which names should be added to NAME_MAPPING.
    """
    # Count frequency of each name
    name_counts = Counter(all_raw_names)

    # Find unmapped names
    unmapped = []
    for name, count in name_counts.items():
        normalized = normalize_for_search(name)
        is_mapped = False
        for map_key in NAME_MAPPING.keys():
            if normalize_for_search(map_key) == normalized:
                is_mapped = True
                break
        if not is_mapped:
            unmapped.append((name, count))

    # Sort by frequency
    unmapped.sort(key=lambda x: x[1], reverse=True)

    print(f"\n📋 Unmapped names report:")
    print(f"   - Total unmapped unique names: {len(unmapped)}")
    print(f"   - Top 20 most frequent unmapped names:")

    for name, count in unmapped[:20]:
        print(f"      '{name}': '',  # {count} mentions")

    # Save full report to CSV
    print(f"\n💾 Saving full unmapped report to {UNMAPPED_REPORT}...")
    with open(UNMAPPED_REPORT, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Name', 'Frequency', 'Suggested Canonical Name (Empty)'])
        for name, count in unmapped:
            writer.writerow([name, count, ''])

    print(f"   ✅ Saved {len(unmapped)} unmapped names to CSV")

def normalize_hadith_data():
    print(f"📚 Loaded {len(NAME_MAPPING)} static mappings from {MAPPINGS_FILE}")
    if CONTEXT_MAPPINGS:
        print(f"🧠 Loaded {len(CONTEXT_MAPPINGS)} context-aware mappings from {CONTEXT_MAPPINGS_FILE}")
    if SPECIAL_CASES:
        print(f"   - Context-dependent names: {len(SPECIAL_CASES.get('context_dependent', []))}")
        print(f"   - Generic names to handle: {len(SPECIAL_CASES.get('too_generic', []))}")

    print(f"\n📂 Loading {INPUT_JSON}...")
    with open(INPUT_JSON, 'r', encoding='utf-8') as f:
        data = json.load(f)

    unique_narrators = {}  # To store ID -> Name mapping
    all_raw_names = []  # Track all narrator mentions for statistics
    context_resolved_count = 0  # True disambiguation (ambiguous name + student context)
    unambiguous_resolved_count = 0  # Simple 1:1 lookups (only one person with this name)
    pronoun_resolved_count = 0  # Pronoun resolution (أبيه → father's name)
    static_resolved_count = 0
    collision_warnings = []

    print("🔄 Normalizing narrator names...")
    for hadith in data:
        if "chains" in hadith and isinstance(hadith["chains"], list):
            for chain in hadith["chains"]:
                narrators = chain["narrators"]
                # Capture raw names BEFORE any modification to ensure
                # context keys use original names (not already-normalized ones)
                raw_names = [n["name"].strip() for n in narrators]

                for i, narrator in enumerate(narrators):
                    raw_name = raw_names[i]
                    all_raw_names.append(raw_name)

                    canonical_name = None

                    # Determine student name for context lookups
                    if i > 0:
                        student_raw = raw_names[i - 1]
                    else:
                        student_raw = "البخاري (بداية السند)"

                    # --- STEP 1: Context JSON lookup (pre-computed mappings) ---
                    if CONTEXT_MAPPINGS:
                        context_key = f"{raw_name}|{student_raw}"
                        if context_key in CONTEXT_MAPPINGS:
                            resolved = CONTEXT_MAPPINGS[context_key]
                            if '(غامض)' not in resolved and '(سياقي)' not in resolved:
                                canonical_name = resolved
                                # Classify by resolution type for honest statistics
                                res_type = get_resolution_type(raw_name)
                                if res_type == 'unambiguous':
                                    unambiguous_resolved_count += 1
                                elif res_type == 'pronoun':
                                    pronoun_resolved_count += 1
                                else:
                                    context_resolved_count += 1

                    # --- STEP 1b: Live rule resolution (covers pairs not in CSV) ---
                    if canonical_name is None:
                        resolved = resolve_ambiguous(raw_name, student_raw)
                        if resolved and '(غامض)' not in resolved and '(سياقي)' not in resolved:
                            canonical_name = resolved
                            # Classify by resolution type for honest statistics
                            res_type = get_resolution_type(raw_name)
                            if res_type == 'unambiguous':
                                unambiguous_resolved_count += 1
                            elif res_type == 'pronoun':
                                pronoun_resolved_count += 1
                            else:
                                context_resolved_count += 1

                    # --- STEP 2: Static mapping fallback ---
                    if canonical_name is None:
                        normalized_name = normalize_for_search(raw_name)
                        for map_key, map_value in NAME_MAPPING.items():
                            if normalize_for_search(map_key) == normalized_name:
                                canonical_name = map_value
                                static_resolved_count += 1
                                break

                    # --- STEP 3: Identity fallback (keep original) ---
                    if canonical_name is None:
                        canonical_name = raw_name

                    # تحديث الاسم في البيانات
                    narrator["original_name"] = raw_name
                    narrator["name"] = canonical_name

                    # ID generation (SHA-256, 12 chars)
                    narrator_id = generate_narrator_id(canonical_name)
                    narrator["id"] = narrator_id

                    # Collision detection
                    if narrator_id in unique_narrators:
                        if unique_narrators[narrator_id] != canonical_name:
                            warning = f"⚠️  ID COLLISION: {narrator_id}\n   Existing: {unique_narrators[narrator_id]}\n   New: {canonical_name}"
                            if warning not in collision_warnings:
                                collision_warnings.append(warning)
                    else:
                        unique_narrators[narrator_id] = canonical_name

    mapped_count = unambiguous_resolved_count + context_resolved_count + pronoun_resolved_count + static_resolved_count

    print(f"\n📊 Statistics:")
    print(f"   - Total narrator mentions: {len(all_raw_names)}")
    print(f"   - Unique narrators (after normalization): {len(unique_narrators)}")
    print(f"   - Unambiguous (1:1 lookup, e.g. عائشة): {unambiguous_resolved_count}")
    print(f"   - Context-disambiguated (student-based, e.g. سفيان): {context_resolved_count}")
    print(f"   - Pronoun-resolved (e.g. أبيه → father): {pronoun_resolved_count}")
    print(f"   - Static-resolved (general mapping): {static_resolved_count}")
    print(f"   - Total mapped: {mapped_count}")

    if len(all_raw_names) > 0:
        coverage = (mapped_count / len(all_raw_names)) * 100
        print(f"   - Coverage: {coverage:.1f}% of mentions mapped")

    if collision_warnings:
        print(f"\n🚨 WARNING: {len(collision_warnings)} ID collisions detected:")
        for warning in collision_warnings[:5]:  # Show first 5
            print(warning)

    # Generate report of unmapped high-frequency names
    generate_unmapped_report(all_raw_names)

    print(f"\n📊 Unique narrators processed: {len(unique_narrators)}")
    
    print(f"\n💾 Saving to {OUTPUT_JSON}...")
    with open(OUTPUT_JSON, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"   ✅ Saved normalized data")

    # حفظ قائمة الرواة النهائية (Nodes List) لسهولة الاستيراد في Neo4j
    nodes_file = "Bukhari/narrators_nodes.csv"
    print(f"\n💾 Saving nodes list to {nodes_file}...")
    with open(nodes_file, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['narrator_id', 'canonical_name'])
        for nid, name in sorted(unique_narrators.items()):
            writer.writerow([nid, name])
    print(f"   ✅ Saved {len(unique_narrators)} unique narrator nodes")

    print("\n" + "="*60)
    print("✅ Normalization Complete!")
    print("="*60)
    print(f"📁 Output files:")
    print(f"   - {OUTPUT_JSON}")
    print(f"   - {nodes_file}")
    print(f"   - {UNMAPPED_REPORT}")
    print("\n💡 Next steps:")
    print("   1. Review unmapped_narrators_report.csv")
    print("   2. Add high-frequency names to NAME_MAPPING dictionary")
    print("   3. Re-run this script to improve coverage")
    print("   4. When satisfied, proceed to Neo4j ingestion")

if __name__ == "__main__":
    normalize_hadith_data()